version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: claude2api-backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    networks:
      - claude2api-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: claude2api-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_ADMIN_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - claude2api-network

networks:
  claude2api-network:
    driver: bridge

volumes:
  config-data: